## 🏋️🐼 Práctica de Data cleaning (pandas) 

Cómo usar este cuaderno:
1. Completa el código en cada reto.
2. Ejecuta el check si existe.
3. Si algo falla, corrige y vuelve a intentar, ¡sin miedo a destruir !

¡Vamos a ello! 

Javi lleva meses registrando sus entrenamientos en un archivo.
El problema: **lo hizo sin ningún orden**. 😅

Fechas raras, datos que faltan, valores imposibles, duplicados...

Nuestra misión: **limpiar el dataset** para que se pueda analizar correctamente. 💪

---

### ¿Qué vamos a practicar?

| Paso | Concepto |
|------|----------|
| 1 | Cargar un CSV con pandas |
| 2 | Explorar y entender los datos |
| 3 | Detectar y eliminar duplicados |
| 4 | Manejar valores nulos |
| 5 | Limpiar y convertir fechas |
| 6 | Detectar y corregir valores erróneos |
| 7 | Análisis final |

> 🌱 **Nivel:** Principiantes del bootcamp  
> ⏱️ **Tiempo estimado:** 50 minutos  
> 🐼 **Librería:** `pandas`

**Nombre:** _______________________  **Fecha:** ___________

---
## 📦 Paso 0 — Importar pandas

Siempre empezamos importando la librería que vamos a usar.

In [1]:
# Ejecuta esta celda (Shift + Enter)
import pandas as pd

print('✅ pandas listo, versión:', pd.__version__)

✅ pandas listo, versión: 3.0.1

In [1]:
import pandas as pd
print ("✅ pandas listo, versión:', pd.__version__")

✅ pandas listo, versión:', pd.__version__

---
## 📂 Paso 1 — Cargar el dataset

El dataset está guardado en un archivo llamado `data.csv`.
Vamos a cargarlo en un DataFrame.

### Ejercicio 1
Carga el archivo `data.csv` usando `pd.read_csv()` y guárdalo en una variable llamada `df`. Luego muéstralo.

> 💡 **Pista:** `pd.read_csv('nombre_del_archivo.csv')`

In [5]:
# ✏️ Carga el CSV aquí
df = pd.read_csv("dataset_gimnasio.csv")


# Muestra el DataFrame
df.to_string()

"    Duration          Date  Pulse  Maxpulse  Calories\n0         60  '2020/12/01'    110       130     409.1\n1         60  '2020/12/02'    117       145     479.0\n2         60  '2020/12/03'    103       135     340.0\n3         45  '2020/12/04'    109       175     282.4\n4         45  '2020/12/05'    117       148     406.0\n5         60  '2020/12/06'    102       127     300.0\n6         60  '2020/12/07'    110       136     374.0\n7        450  '2020/12/08'    104       134     253.3\n8         30  '2020/12/09'    109       133     195.1\n9         60  '2020/12/10'     98       124     269.0\n10        60  '2020/12/11'    103       147     329.3\n11        60  '2020/12/12'    100       120     250.7\n12        60  '2020/12/12'    100       120     250.7\n13        60  '2020/12/13'    106       128     345.3\n14        60  '2020/12/14'    104       132     379.3\n15        60  '2020/12/15'     98       123     275.0\n16        60  '2020/12/16'     98       120     215.2\n17        60  '2020/12/17'    100       120     300.0\n18        45  '2020/12/18'     90       112       NaN\n19        60  '2020/12/19'    103       123     323.0\n20        45  '2020/12/20'     97       125     243.0\n21        60  '2020/12/21'    108       131     364.2\n22        45           NaN    100       119     282.0\n23        60  '2020/12/23'    130       101     300.0\n24        45  '2020/12/24'    105       132     246.0\n25        60  '2020/12/25'    102       126     334.5\n26        60      20201226    100       120     250.0\n27        60  '2020/12/27'     92       118     241.0\n28        60  '2020/12/28'    103       132       NaN\n29        60  '2020/12/29'    100       132     280.0\n30        60  '2020/12/30'    102       129     380.3\n31        60  '2020/12/31'     92       115     243.0"

### 🤔 Pregunta 1
Observa el DataFrame. Anota todos los problemas que veas (doble clic para editar):

| # | Columna | Problema que veo |
|---|---------|------------------|
| 1 | duracion  |en la fila 7 la duración es excesiva |
| 2 | varias| |Fila 11 y 12 registros duplicados
| 3 | Fecha| |Fila 22 formato de fecha erróneo
| 4 | calorias| fila 18 formato de número erróneo|
| 5 | | |

In [6]:
print(df.iloc[0:26].to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5

---
## 🔍 Paso 2 — Explorar los datos

Antes de limpiar, hay que **entender bien** lo que tenemos.

### Ejercicio 2.1 — ¿Cuántos registros hay?
Muestra las **dimensiones** del DataFrame (filas y columnas).

> 💡 **Pista:** `.shape`

In [8]:
# ✏️ Tu código aquí
df . shape

(32, 5)

### Ejercicio 2.2 — ¿Qué tipo de datos tiene cada columna?

> 💡 **Pista:** `.dtypes`  
> Recuerda: `object`= texto, `int64` = entero, `float64` = decimal

In [9]:
# ✏️ Tu código aquí
df . dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

### Ejercicio 2.3 — ¿Cuántos valores faltan?
Cuenta los valores nulos en cada columna.

> 💡 **Pista:** `.isnull().sum()`

In [12]:
# ✏️ Tu código aquí
df .isnull ().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

### Ejercicio 2.4 — Estadísticas básicas
Muestra un resumen estadístico del DataFrame (mínimo, máximo, media...).

> 💡 **Pista:** `.describe()`

In [13]:
# ✏️ Tu código aquí
df .describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

### 🤔 Pregunta 2
Fíjate en el valor **máximo de `Duration`**. ¿Te parece normal? ¿Qué crees que pasó?

_(escribe tu respuesta aquí)_

In [14]:
# Creo que ha cometido un error y ha puesto un cero de más#

---
## 🎯 Paso 3 — Eliminar duplicados

Parece que algún entrenamiento se registró dos veces.

### Ejercicio 3.1 — Encontrar los duplicados
Muestra las filas que están repetidas.

> 💡 **Pista:** `df[df.duplicated(keep=False)]`  
> `keep=False` marca **todas** las copias como duplicadas

In [15]:
# ✏️ Muestra las filas duplicadas
df[df .duplicated(keep=False)]

    Duration          Date  Pulse  Maxpulse  Calories
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7

### Ejercicio 3.2 — Eliminar los duplicados
Quédate solo con la primera aparición y reinicia el índice.

> 💡 **Pistas:**
> - `.drop_duplicates()` elimina duplicados
> - `.reset_index(drop=True)` reinicia el índice
> - Recuerda guardar: `df = ...`

In [20]:
# ✏️ Elimina duplicados y reinicia el índice
df = df .drop_duplicates() .reset_index(drop=True)



print('Filas después de eliminar duplicados:', len(df))

Filas después de eliminar duplicados: 31

---
## 🕳️ Paso 4 — Manejar valores nulos

Tenemos valores nulos en `Date` y `Calories`. Los trataremos de forma diferente.

### Ejercicio 4.1 — Ver las filas con nulos
Muestra solo las filas que tienen algún valor nulo.

> 💡 **Pista:** `df[df.isnull().any(axis=1)]`  
> `axis=1` significa "busca en cada fila"

In [21]:
# ✏️ Muestra las filas con nulos
df [df .isnull() .any(axis=1)]

    Duration          Date  Pulse  Maxpulse  Calories
17        45  '2020/12/18'     90       112       NaN
21        45           NaN    100       119     282.0
27        60  '2020/12/28'    103       132       NaN

### Ejercicio 4.2 — Rellenar Calories con la media
Rellena los huecos de `Calories` con la media de esa columna, redondeada a 1 decimal.

> 💡 **Pistas:**
> - Calcula primero: `df['Calories'].mean()`
> - Redondea: `round(media, 1)`
> - Rellena: `.fillna(valor)`

In [25]:
# ✏️ Calcula la media e imprímela
media_calorias = df ["Calories"] .mean()
df ["Calories"] = df ["Calories"] .fillna(round(media_calorias , 1))





print('Nulos en Calories:', df['Calories'].isnull().sum())

Nulos en Calories: 0

### Ejercicio 4.3 — Eliminar la fila con Date nula
La fila que no tiene fecha no nos sirve. Elimínala y reinicia el índice.

> 💡 **Pistas:**
> - `.dropna(subset=['Date'])` elimina filas con nulo en Date
> - `.reset_index(drop=True)`

In [26]:
# ✏️ Elimina la fila sin fecha
df = df .dropna(subset=["Date"])
df = df .reset_index(drop=True)


print('Filas restantes:', len(df))
print('Nulos totales:', df.isnull().sum().sum())

Filas restantes: 30
Nulos totales: 0

---
## 📅 Paso 5 — Limpiar la columna de fechas

La columna `Date` tiene un problema: la mayoría de fechas tienen comillas (`'2020/12/01'`) y **una** tiene un formato completamente diferente (`20201226`).

### Ejercicio 5.1 — Ver los valores únicos de Date
Imprime todos los valores de la columna `Date` para ver el problema.

> 💡 **Pista:** `df['Date'].tolist()`

In [30]:
import pandas as pd
# 1 volvemos a cargar los datos
df = pd.read_csv("dataset_gimnasio.csv")
# 2 Quitamos duplicados
df = df.drop_duplicates().reset_index(drop=True)
# 3 Arreglamos las Calorias (rellenar nulos con la media)
df["Calories"] = df["Calories"].fillna(df["Calories"].mean()).round(2)
# 4 Arreglamos las fechas (convertir a formato real y quitar nulos)
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna(subset=["Date"]).reset_index(drop=True)
# 5 Corregimos el error de las 7 hors (el 450)  
df . loc[df["Duration"] == 450, "Duration"] = 45  

# --- COMPROBACIÓN FINAL ---
print("✅ ¡Tabla limpia!")
print(f"Filas finales: {len(df)}")
print(df.head(10)) # Vemos las primeras 10 filas
df.to_csv("datos_limpios.csv", index=False)

✅ ¡Tabla limpia!
Filas finales: 29
   Duration       Date  Pulse  Maxpulse  Calories
0        60 2020-12-01    110       130     409.1
1        60 2020-12-02    117       145     479.0
2        60 2020-12-03    103       135     340.0
3        45 2020-12-04    109       175     282.4
4        45 2020-12-05    117       148     406.0
5        60 2020-12-06    102       127     300.0
6        60 2020-12-07    110       136     374.0
7        45 2020-12-08    104       134     253.3
8        30 2020-12-09    109       133     195.1
9        60 2020-12-10     98       124     269.0

In [31]:
# ✏️ Muestra todos los valores de Date
# 1. Convertimos la columna Date a una lista y la guardamos en una variable nueva
lista_fechas = df["Date"].tolist()

# 2. Mostramos la lista completa
print("Valores de la columna Date:")
print(lista_fechas)

Valores de la columna Date:
[Timestamp('2020-12-01 00:00:00'), Timestamp('2020-12-02 00:00:00'), Timestamp('2020-12-03 00:00:00'), Timestamp('2020-12-04 00:00:00'), Timestamp('2020-12-05 00:00:00'), Timestamp('2020-12-06 00:00:00'), Timestamp('2020-12-07 00:00:00'), Timestamp('2020-12-08 00:00:00'), Timestamp('2020-12-09 00:00:00'), Timestamp('2020-12-10 00:00:00'), Timestamp('2020-12-11 00:00:00'), Timestamp('2020-12-12 00:00:00'), Timestamp('2020-12-13 00:00:00'), Timestamp('2020-12-14 00:00:00'), Timestamp('2020-12-15 00:00:00'), Timestamp('2020-12-16 00:00:00'), Timestamp('2020-12-17 00:00:00'), Timestamp('2020-12-18 00:00:00'), Timestamp('2020-12-19 00:00:00'), Timestamp('2020-12-20 00:00:00'), Timestamp('2020-12-21 00:00:00'), Timestamp('2020-12-23 00:00:00'), Timestamp('2020-12-24 00:00:00'), Timestamp('2020-12-25 00:00:00'), Timestamp('2020-12-27 00:00:00'), Timestamp('2020-12-28 00:00:00'), Timestamp('2020-12-29 00:00:00'), Timestamp('2020-12-30 00:00:00'), Timestamp('2020-12-31 00:00:00')]

In [32]:
import pandas as pd

# 1. Cargar datos
df = pd.read_csv("dataset_gimnasio.csv")

# 2. Limpieza que ya hemos hecho (Duplicados y Calorías)
df = df.drop_duplicates().reset_index(drop=True)
df["Calories"] = df["Calories"].fillna(df["Calories"].mean()).round(2)

# 3. Paso 5.1: Arreglar el formato de las fechas
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# 4. LA PISTA DEL EJERCICIO (Lo que quieres pegar ahora)
# Esto te mostrará la línea larga con todos los Timestamps
print("Lista de fechas convertidas:")
print(df["Date"].tolist())

# 5. Ver la tabla "bonita" para confirmar que no se ha roto
print("\nVista previa de la tabla:")
print(df.head())

Lista de fechas convertidas:
[Timestamp('2020-12-01 00:00:00'), Timestamp('2020-12-02 00:00:00'), Timestamp('2020-12-03 00:00:00'), Timestamp('2020-12-04 00:00:00'), Timestamp('2020-12-05 00:00:00'), Timestamp('2020-12-06 00:00:00'), Timestamp('2020-12-07 00:00:00'), Timestamp('2020-12-08 00:00:00'), Timestamp('2020-12-09 00:00:00'), Timestamp('2020-12-10 00:00:00'), Timestamp('2020-12-11 00:00:00'), Timestamp('2020-12-12 00:00:00'), Timestamp('2020-12-13 00:00:00'), Timestamp('2020-12-14 00:00:00'), Timestamp('2020-12-15 00:00:00'), Timestamp('2020-12-16 00:00:00'), Timestamp('2020-12-17 00:00:00'), Timestamp('2020-12-18 00:00:00'), Timestamp('2020-12-19 00:00:00'), Timestamp('2020-12-20 00:00:00'), Timestamp('2020-12-21 00:00:00'), NaT, Timestamp('2020-12-23 00:00:00'), Timestamp('2020-12-24 00:00:00'), Timestamp('2020-12-25 00:00:00'), NaT, Timestamp('2020-12-27 00:00:00'), Timestamp('2020-12-28 00:00:00'), Timestamp('2020-12-29 00:00:00'), Timestamp('2020-12-30 00:00:00'), Timestamp('2020-12-31 00:00:00')]

Vista previa de la tabla:
   Duration       Date  Pulse  Maxpulse  Calories
0        60 2020-12-01    110       130     409.1
1        60 2020-12-02    117       145     479.0
2        60 2020-12-03    103       135     340.0
3        45 2020-12-04    109       175     282.4
4        45 2020-12-05    117       148     406.0

### Ejercicio 5.2 — Eliminar las comillas
Elimina las comillas simples (`'`) que rodean las fechas.

> 💡 **Pista:** `.str.replace("'", '', regex=False)`

In [5]:
# ✏️ Elimina las comillas de la columna Date
# Quita las comillas de la columna 'Nombre'
import pandas as pd

# 1. Cargamos el archivo (para que 'df' esté definido)
df = pd.read_csv('dataset_gimnasio.csv')

# 2. EJERCICIO 5.2: Solo eliminar las comillas de la columna Date
# Usamos astype(str) para que no falle con la fila que no tiene comillas
df['Date'] = df['Date'].astype(str).str.replace("'", "", regex=False)

# 3. Comprobamos el resultado (verás que el 20201226 sigue ahí, pero sin comillas los demás)
print(df['Date'].unique())

<StringArray>
['2020/12/01', '2020/12/02', '2020/12/03', '2020/12/04', '2020/12/05',
 '2020/12/06', '2020/12/07', '2020/12/08', '2020/12/09', '2020/12/10',
 '2020/12/11', '2020/12/12', '2020/12/13', '2020/12/14', '2020/12/15',
 '2020/12/16', '2020/12/17', '2020/12/18', '2020/12/19', '2020/12/20',
 '2020/12/21',          nan, '2020/12/23', '2020/12/24', '2020/12/25',
   '20201226', '2020/12/27', '2020/12/28', '2020/12/29', '2020/12/30',
 '2020/12/31']
Length: 31, dtype: str

### Ejercicio 5.3 — Convertir al tipo fecha
Convierte `Date` al tipo de dato `datetime` de pandas.

> 💡 **Pista:** `pd.to_datetime(df['Date'], infer_datetime_format=True)`  
> Con `infer_datetime_format=True` pandas intenta detectar el formato solo

In [6]:
# ✏️ Convierte Date a datetime
df['Date'] = pd.to_datetime(df['Date'], format='mixed')


print('Tipo de Date:', df['Date'].dtype)
print(df['Date'].tolist())

Tipo de Date: datetime64[us]
[Timestamp('2020-12-01 00:00:00'), Timestamp('2020-12-02 00:00:00'), Timestamp('2020-12-03 00:00:00'), Timestamp('2020-12-04 00:00:00'), Timestamp('2020-12-05 00:00:00'), Timestamp('2020-12-06 00:00:00'), Timestamp('2020-12-07 00:00:00'), Timestamp('2020-12-08 00:00:00'), Timestamp('2020-12-09 00:00:00'), Timestamp('2020-12-10 00:00:00'), Timestamp('2020-12-11 00:00:00'), Timestamp('2020-12-12 00:00:00'), Timestamp('2020-12-12 00:00:00'), Timestamp('2020-12-13 00:00:00'), Timestamp('2020-12-14 00:00:00'), Timestamp('2020-12-15 00:00:00'), Timestamp('2020-12-16 00:00:00'), Timestamp('2020-12-17 00:00:00'), Timestamp('2020-12-18 00:00:00'), Timestamp('2020-12-19 00:00:00'), Timestamp('2020-12-20 00:00:00'), Timestamp('2020-12-21 00:00:00'), NaT, Timestamp('2020-12-23 00:00:00'), Timestamp('2020-12-24 00:00:00'), Timestamp('2020-12-25 00:00:00'), Timestamp('2020-12-26 00:00:00'), Timestamp('2020-12-27 00:00:00'), Timestamp('2020-12-28 00:00:00'), Timestamp('2020-12-29 00:00:00'), Timestamp('2020-12-30 00:00:00'), Timestamp('2020-12-31 00:00:00')]

In [7]:
df . head()

   Duration       Date  Pulse  Maxpulse  Calories
0        60 2020-12-01    110       130     409.1
1        60 2020-12-02    117       145     479.0
2        60 2020-12-03    103       135     340.0
3        45 2020-12-04    109       175     282.4
4        45 2020-12-05    117       148     406.0

---
## 🚨 Paso 6 — Detectar y corregir valores erróneos

Cuando revisaste el `.describe()`, ¿viste algo raro en `Duration`?
Hay un entrenamiento registrado con **450 minutos** (¡7 horas y media!) 😱

### Ejercicio 6.1 — Ver la fila problemática
Muestra la fila donde `Duration` es mayor que 120 minutos.

> 💡 **Pista:** `df[df['Duration'] > 120]`

In [13]:
# ✏️ Muestra las filas con Duration > 
print (df[df['Duration'] > 120])

   Duration       Date  Pulse  Maxpulse  Calories
7       450 2020-12-08    104       134     253.3

### 🤔 Pregunta 3
El valor es `450`. ¿Qué crees que pasó? Marca la opción que te parece más probable:

- [ ] Fue un error tipográfico (quería escribir `45`)
- [ ] El entrenamiento duró de verdad 450 minutos
- [ ] El dato proviene de otra unidad de medida

_(escribe tu razonamiento aquí)_

In [ ]:
#Creo que se debe a un error humano, se añadió un cero de más

### Ejercicio 6.2 — Corregir el valor
Reemplaza el valor `450` por `45` en la columna `Duration`.

> 💡 **Pista:** `df['Duration'] = df['Duration'].replace(450, 45)`

In [14]:
# ✏️ Corrige el valor 450 → 
# 1. Aplicamos el cambio en toda la columna sin importar la fila
df['Duration'] = df['Duration'].replace(450, 45)


print('Duración máxima ahora:', df['Duration'].max(), 'minutos')

Duración máxima ahora: 60 minutos

### Ejercicio 6.3 — Revisar Maxpulse
Hay una fila donde el pulso máximo (`Maxpulse`) es **menor** que el pulso normal (`Pulse`). ¡Eso es imposible fisiológicamente!

Encuéntrala.

> 💡 **Pista:** `df[df['Maxpulse'] < df['Pulse']]`

In [16]:
# 1. Vamos a ver las dos columnas juntas para comparar a ojo
print("Primeras filas de Pulse y Maxpulse:")
print(df[['Pulse', 'Maxpulse']].head(15))

# 2. Vamos a comprobar si hay valores nulos que estén fastidiando la comparación
print("\n¿Hay nulos en estas columnas?")
print(df[['Pulse', 'Maxpulse']].isnull().sum())

Primeras filas de Pulse y Maxpulse:
    Pulse  Maxpulse
0     110       130
1     117       145
2     103       135
3     109       175
4     117       148
5     102       127
6     110       136
7     104       134
8     109       133
9      98       124
10    103       147
11    100       120
12    100       120
13    106       128
14    104       132

¿Hay nulos en estas columnas?
Pulse       0
Maxpulse    0
dtype: int64

In [ ]:
# ✏️ Encuentra la fila donde Maxpulse < Pulse
# ✏️ Buscamos con <= (menor o igual)
filas_error_pulso = df[df['Maxpulse'] <= df['Pulse']]

print("Resultado de la búsqueda con <= :")
print(filas_error_pulso)

Resultado de la búsqueda con <= :
    Duration       Date  Pulse  Maxpulse  Calories
23        60 2020-12-23    130       101     300.0

### Ejercicio 6.4 — Eliminar la fila incorrecta
Esa fila tiene datos imposibles. Elimínala y reinicia el índice.

> 💡 **Pista:** quédate con las filas donde `Maxpulse >= Pulse`  
> `df = df[df['Maxpulse'] >= df['Pulse']].reset_index(drop=True)`

In [18]:
# ✏️ Elimina la fila con Maxpulse < Pulse
# ✏️ 6.4: Filtramos para quedarnos solo con los datos lógicos
# Y reiniciamos el índice para que no falte el número 23 en la lista
df = df[df['Maxpulse'] >= df['Pulse']].reset_index(drop=True)

# Comprobamos que la fila problemática ha desaparecido
# Y vemos cuántas filas tenemos ahora
print("Nuevo número de filas:", len(df))
print("\nPrimeras filas tras la limpieza:")
df.head(25) # Miramos hasta la 25 para ver que el índice es correlativo


print('Filas en el dataset limpio:', len(df))

Nuevo número de filas: 31

Primeras filas tras la limpieza:
Filas en el dataset limpio: 31

---
## 🏆 Paso 7 — Dataset limpio y análisis final

### Ejercicio 7.1 — Ver el resultado final
Muestra el DataFrame limpio completo.

In [23]:
# ✏️ Muestra el DataFrame final
# --- LIMPIEZA FINAL ---
# 1. Borrar duplicados
df.drop_duplicates(inplace=True)

# 2. Borrar la fila con fecha NaT (la 22)
df.dropna(subset=['Date'], inplace=True)

# 3. Rellenar calorías vacías con la media
df.fillna({'Calories': df['Calories'].mean()}, inplace=True)
# Redondear las calorías a 2 decimales para que quede más bonito
df['Calories'] = df['Calories'].round(2)


# 4. Resetear el índice por última vez para que sea perfecto
df.reset_index(drop=True, inplace=True)

# Mostrar el resultado final
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-13    106       128    345.30
13        60 2020-12-14    104       132    379.30
14        60 2020-12-15     98       123    275.00
15        60 2020-12-16     98       120    215.20
16        60 2020-12-17    100       120    300.00
17        45 2020-12-18     90       112    307.69
18        60 2020-12-19    103       123    323.00
19        45 2020-12-20     97       125    243.00
20        60 2020-12-21    108       131    364.20
21        45 2020-12-24    105       132    246.00
22        60 2020-12-25    102       126    334.50
23        60 2020-12-26    100       120    250.00
24        60 2020-12-27     92       118    241.00
25        60 2020-12-28    103       132    307.69
26        60 2020-12-29    100       132    280.00
27        60 2020-12-30    102       129    380.30
28        60 2020-12-31     92       115    243.00

### Ejercicio 7.2 — Preguntas de análisis
Usa el DataFrame limpio para responder:

In [26]:
# 🔥 ¿Cuántas calorías quemó en total?
# Pista: .sum()
Total_calorias = df['Calories'] . sum()
print(f"En total, Javi quemó {Total_calorias:.2f} calorías en todo el mes.")

En total, Javi quemó 8923.08 calorías en todo el mes.

In [30]:
# 💓 ¿Cuál fue el pulso medio durante los entrenamientos?
# Pista: .mean() y round()
pulso_medio_total = df['Pulse'] .mean()
pulso_medio_redondeado = round (pulso_medio_total, 2)
print (pulso_medio_redondeado)

102.83

In [31]:
# 🏅 ¿En qué fecha quemó más calorías?
# Pista: filtra la fila con el máximo de Calories usando .idxmax()
# df.loc[df['Calories'].idxmax()]
# 🏅 Buscamos la fila con el máximo de calorías
fila_record = df.loc[df['Calories'].idxmax()]

print("El día que más calorías quemó fue:")
print(fila_record)

# Si solo quieres la fecha específica:
print(f"\nLa fecha exacta fue: {fila_record['Date']}")

El día que más calorías quemó fue:
Duration                     60
Date        2020-12-02 00:00:00
Pulse                       117
Maxpulse                    145
Calories                  479.0
Name: 1, dtype: object

La fecha exacta fue: 2020-12-02 00:00:00

In [32]:
# ⏱️ ¿Cuántos entrenamientos duraron exactamente 60 minutos?
# ✏️ Contamos cuántas sesiones duraron exactamente 60 minutos
sesiones_60 = len(df[df['Duration'] == 60])

print(f"Javi realizó {sesiones_60} entrenamientos de exactamente 60 minutos.")

Javi realizó 22 entrenamientos de exactamente 60 minutos.

---
## 📝 Resumen final — Completa la tabla

Rellena con lo que has aprendido hoy (doble clic para editar):

| Problema encontrado | Método de pandas que usé |
|---------------------|---------------------------|
| Cargar un archivo CSV |pd.read_csv('archivo.csv') |
| Ver dimensiones del DataFrame |df.shape |
| Ver tipos de datos | df.info() o df.dtypes|
| Contar valores nulos |df.isnull().sum() |
| Ver estadísticas básicas |df.describe() |
| Eliminar filas duplicadas | df.drop_duplicates(inplace=True)|
| Rellenar valores nulos con la media |df['col'].fillna(df['col'].mean(), inplace=True) |
| Eliminar filas con nulos |df.dropna(subset=['col'], inplace=True) |
| Limpiar texto en una columna |df['col'].str.replace("'", "") |
| Convertir texto a fecha | pd.to_datetime(df['col'], format='mixed')|
| Corregir un valor erróneo |df.loc[7, 'Duration'] = 45 |
| Filtrar filas por condición |df[df['Duration'] > 120] |

---
### 💪 ¡El dataset está limpio y listo para analizar. Buen trabajo!